### ISSUE TITLE
parse_error!': got incomplete JSON hash configuration at td-agent.conf (Fluent::ConfigParseError)

### ISSUE THREAD

**Issue by EngineerMarion** [EngineerMarion/FluentD-Coralogix-Logs#1]
I plan to push plain text logs from my local linux machine (redhat8) to Coralogix. 

1. Initial Deployment Testing
1.1. My initial deployment is that I've used tail, as an input plugin in fluentd, to read the plain text file and output it to a local file using file output plugin in fluentd
1.2. Results: The outcome was successful.
-->From here, I know that my fluentd is installed correctly and has the correct permissions necessary to function successfully.

2. Sending logs to Coralogix [My concern]
2.1. I've used the Coralogix guide for deployment but wasn't able to push logs via fluentd successfully
2.2. Config:

<Source>

 @type tail
 @id tail_var_logs
 @label @CORALOGIX
 read_from_head true
 tag application.log
 path /var/log/myfile.log
 pos_file /var/log/td-agent/tmp/coralog.pos
     path_key path
 <parse>
   @type none
 </parse>
</source>

<label @CORALOGIX>

  <filter application.log>
  @type record_transformer
  @log_level warn
  enable_ruby true
  auto_typecast true
  renew_record true
  <record>
    applicationName "Example_App"
    subsystemName "Example_Subsystem"
    text ${record.to_json}
  </record>
  </filter>

<match application.log>

  @type http
  endpoint https://api.coralogix.com/logs/rest/singles
  headers {"private_key":<my private key>}
  retryable_response_codes 503
  error_response_as_unrecoverable false
  <buffer>
    @type memory
    chunk_limit_size 10MB
    compress gzip
    flush_interval 1s
    retry_max_times 5
    retry_type periodic
    retry_wait 2
  </buffer>
  <secondary>
    #If any messages fail to send they will be send to STDOUT for debug.
    @type stdout
  </secondary>
</match>
</label>

~~From there when I restart the td agent, the error comes like this:

ERROR Logs:

 from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/config/literal_parser.rb:279:in `scan_json'
/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.3/lib/fluent/config/basic_parser.rb:92:in `parse_error!': got incomplete JSON hash configuration at td-agent.conf line 165,10 (Fluent::ConfigParseError)

(Using td-agent --dry-run command)

**Comment by EngineerMarion** [comment]
I have resolved the issue by quoting the private key.
